/* Progressive feature hub: existing destinations plus canonical grouped entries. */
function createAllView(navigate,options={}){
 const U=PWFeatureUI,{el,button,heading}=PWUI,root=el('div','pw-screen pw-all pw-all-hub');root.append(heading('전체 메뉴'));let disposed=false,observer,frame;
 const core=[['home','홈'],['record','기록'],['goal','목표'],['report','리포트']],groups=[['money','내 돈',['record','goal','calendar','thoughtbox']],['habit','나의 습관',['report','coaching','badges','streak']],['together','함께하기',['parent-view','rewards','family-connection','family-permissions','next-plan']],['learning','배우기',['quiz']],['convenience','편의 기능',['notifications','receipt','allowance','reflection','category-suggestion']],['settings','설정',['profile','settings','privacy','notification-settings','data','finance','card','app-info']],['ai','AI 기능',['habit-analysis','coaching','ai-report','parent-view','next-plan','quiz']]];
 const selected=groups.find(g=>g[0]===options.group);const top=el('div','pw-all-shortcuts');
 if(!selected){for(const [id,label]of core){const b=button(label,()=>navigate(id),'pw-all-shortcut');b.dataset.screen=id;top.append(b);}const grid=el('div','pw-all-groups');for(const [id,label,items]of groups){const b=button('',()=>navigate({screen:'all',group:id}),'pw-all-group');b.dataset.group=id;const icon=el('span');if(id==='money')icon.append(pwIllustrationPanel('all',{panelClass:'pw-all-hub-art pw-compact-visual',ambient:false}));else icon.innerHTML=pwIcon('all');b.append(icon,el('span','',label),el('span','pw-meta',items.length+'개'));grid.append(b);}const optionsBar=el('div','pw-app-options'),hint=el('p','pw-app-hint');hint.setAttribute('role','status');const demo=button(PWDemo.enabled?'실제 기록 보기':'가상 데이터 보기',()=>PWDemo.toggle(),'pw-button pw-button--secondary'),full=button('전체 화면',()=>PWViewport.fullscreen(hint),'pw-button pw-button--secondary');optionsBar.append(demo,full,hint);root.append(top,grid,optionsBar);}
 else {top.classList.add('pw-all-subheader');const back=U.action('‹ 전체 메뉴',()=>PWNavigation.back({screen:'all'}),true);top.append(back,el('h2','',selected[1]));const panel=el('div','pw-all-group-content'),list=el('div','pw-all-group-list'),paging=el('nav','pw-pagination');paging.setAttribute('aria-label','기능 메뉴 페이지');let page=1,capacity=4;const label=el('span','pw-meta');label.setAttribute('role','status');const prev=U.action('이전',()=>{page--;paint();list.querySelector('button')?.focus();},true),next=U.action('다음',()=>{page++;paint();list.querySelector('button')?.focus();},true);paging.append(prev,label,next);panel.append(list,paging);root.append(top,panel);
  function paint(){const pages=Math.max(1,Math.ceil(selected[2].length/capacity));page=Math.max(1,Math.min(pages,page));list.replaceChildren();for(const id of selected[2].slice((page-1)*capacity,page*capacity)){const native=PW_TABS.find(t=>t.id===id),info=PW_FEATURES[id],b=button('',()=>navigate(native?{screen:id}:pwFeatureRoute(id,{screen:'all',group:selected[0]})),'pw-all-feature-row');b.dataset.featureLink=id;b.append(el('span','pw-all-feature-label',native?.label||info.title),U.chip(native?'active':info.state,native?'이 기기에 저장':undefined));list.append(b);}prev.disabled=page<=1;next.disabled=page>=pages;label.textContent=page+' / '+pages;}
  function measure(){if(disposed||!list.isConnected)return;const count=document.documentElement.classList.contains('pw-accessible')?selected[2].length:Math.max(1,Math.min(6,Math.floor((list.clientHeight+8)/68)));if(count!==capacity){capacity=count;paint();}}
  paint();observer=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(measure);});
  return {element:root,mount(){observer.observe(list);measure();},dispose(){disposed=true;observer.disconnect();cancelAnimationFrame(frame);}};
 }
 return {element:root,mount(){},dispose(){disposed=true;}};
}
