/* Static fixture quiz. No generation, personalization, reward or finance mutations. */
PWFeatureViews.quiz=(loaded,navigate,options)=>{
 const U=PWFeatureUI,p=U.page('quiz',loaded,navigate,options),d=p.vm.data;let stage='intro',index=0,answers=[],revealed=[];
 const content=U.el('div','pw-quiz-content');p.body.append(content);
 function focus(){const h=content.querySelector('h3');if(h){h.tabIndex=-1;h.focus({preventScroll:false});}PWUI.refreshMotion(p.element);}
 function render(){content.replaceChildren();p.footer.replaceChildren();p.element.dataset.quizStage=stage;
  if(stage==='intro'){content.append(U.card('오늘의 금융 퀴즈',U.row('주제',d.topic),U.row('난이도',d.difficulty),U.row('예상 문제 수',d.questions.length?d.questions.length+'개 · 예제':'준비 중'),U.el('p','pw-muted','맞춤 문제 생성과 난이도 개인화는 연결되지 않았어요.')));if(!U.ready(p.vm)||!d.questions.length){content.append(U.state(p.vm,{profile:'report'}));p.footer.append(U.link('학습과 기록 살펴보기','habit-analysis',navigate,options));}else p.footer.append(U.action('예제 퀴즈 시작',()=>{stage='question';render();focus();}));return;}
  if(stage==='complete'){const count=d.questions.filter((q,i)=>answers[i]===q.answer).length;content.append(pwIllustrationPanel('success',{panelClass:'pw-feature-art pw-compact-visual',ambient:false,idle:false}),U.card('예제 퀴즈를 마쳤어요',U.el('p','pw-feature-score',count+' / '+d.questions.length),U.el('p','pw-muted','활동 포인트·습관 점수·보상은 바뀌지 않아요.')),U.card('배운 내용',...d.learning.map(t=>U.el('p','pw-muted',t))),U.card('다음 추천 학습 · 예시',U.el('p','pw-muted',d.nextLearning||'다음 학습 준비 중')));p.footer.append(U.action('다시 살펴보기',()=>{stage='intro';index=0;answers=[];revealed=[];render();focus();},true),U.link('다음 계획','next-plan',navigate,options));return;}
  const q=d.questions[index],section=U.card(q.question,U.row('진행',`${index+1} / ${d.questions.length}`),U.meter((index+1)/d.questions.length*100,'예제 퀴즈 문제 진행'));content.append(section);
  if(stage==='question'){const group=U.el('fieldset','pw-quiz-options');group.style.border='0';group.style.padding='0';group.append(U.el('legend','pw-sr-only','답을 하나 골라주세요.'));q.options.forEach((text,i)=>{const choice=U.button(text,()=>{answers[index]=i;render();content.querySelector('[data-choice="'+i+'"]').focus({preventScroll:false});},'pw-feature-option');choice.dataset.choice=i;choice.setAttribute('aria-pressed',String(answers[index]===i));group.append(choice);});section.append(group);const prev=U.action('이전',()=>{if(index>0){index--;stage='question';}else stage='intro';render();focus();},true),check=U.action('정답 설명 보기',()=>{revealed[index]=true;stage='explanation';render();focus();if(answers[index]===q.answer)PocketWONMotion.controllerFor(p.element)?.success(p.element.querySelector('.pw-sprite'));});check.disabled=answers[index]===undefined;p.footer.append(prev,check);
  }else {section.append(pwIllustrationPanel(answers[index]===q.answer?'success':'report',{panelClass:'pw-feature-art pw-compact-visual',ambient:false,idle:false}),U.chip('preview',answers[index]===q.answer?'예제 정답이에요':'다시 함께 살펴봐요'),U.row('정답',q.options[q.answer]),U.el('p','',q.explanation),U.accordion('왜 그런가요?',[q.why]));p.footer.append(U.action('선택 다시 보기',()=>{stage='question';render();focus();},true),U.action(index+1===d.questions.length?'완료 보기':'다음 문제',()=>{if(index+1===d.questions.length)stage='complete';else{index++;stage='question';}render();focus();}));}
 }
 render();return p;
};
